---
- name: get angular seed project
  git: accept_hostkey=true repo=git@github.com:Abrahanfer/angular-hackernews.git dest=~/angular-hackernews
- name: create alias for nodejs to node
  sudo: yes
  shell: ln -sf /usr/bin/nodejs /usr/bin/node
- name: install dependencies with nodejs
 # sudo: yes
#  sudo_user: vagrant
  shell: cd ~/angular-hackernews &&  npm install